// account actions
const SIGN = 'SIGN';
const SIGN_SUCCESS = 'SIGN_SUCCESS';
const SIGN_FAILURE = 'SIGN_FAILURE';
const GET_STATUS = 'GET_STATUS';
const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

// task actions
const GET_TASKS = 'GET_TASKS';
const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
const GET_TASKS_FAILURE = 'GET_TASKS_FAILURE';

// record actions
const GET_TASK_RECORDS = 'GET_TASK_RECORDS';
const GET_TASK_RECORDS_SUCCESS = 'GET_TASKS_RECORDS_SUCCESS';
const GET_TASK_RECORDS_FAILURE = 'GET_TASK_RECORDS_FAILURE';

export {
  SIGN,
  SIGN_SUCCESS,
  SIGN_FAILURE,
  GET_STATUS,
  GET_TASKS,
  GET_TASKS_SUCCESS,
  GET_TASKS_FAILURE,
  GET_TASK_RECORDS,
  GET_TASK_RECORDS_SUCCESS,
  GET_TASK_RECORDS_FAILURE,
  DELETE_USER_SUCCESS,
  DELETE_USER_FAILURE,
};
