// account actions
const SIGN = "SIGN";
const SIGN_SUCCESS = "SIGN_SUCCESS";
const SIGN_FAILURE = "SIGN_FAILURE";
const GET_STATUS = "GET_STATUS";

// task actions
const GET_TASKS = "GET_TASKS";
const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
const GET_TASKS_FAILURE = "GET_TASKS_FAILURE";

export {
  SIGN,
  SIGN_SUCCESS,
  SIGN_FAILURE,
  GET_STATUS,
  GET_TASKS,
  GET_TASKS_SUCCESS,
  GET_TASKS_FAILURE
};
